### ISSUE TITLE
[8] Come utente, vorrei che il contatore si aggiornasse in tempo reale (o quasi) perché lo troverei più soddisfacente.

### ISSUE THREAD

**Issue by wbigger** [marconicivitavecchia/IFC-Backend-dev#1]
Capire se è possibile minimizzare i tempi di recupero ed invio dei dati.

**Comment by wbigger** [comment]
La parola chiave è "Instagram Scraper". Uno che va a dati invece che giorni è sicuramente meglio. Se mi fate sapere uno da acquistare provvedo.

**Comment by Kylessh** [comment]
A livello di blocco dell'IP, non avremmo problemi a fare un polling ogni secondo dato che usiamo un rotating proxy. Il problema è che già ora utilizziamo parecchi dati, e facendo richieste con un intervallo troppo basso finiremmo i giga subito.

**Comment by Kylessh** [comment]
Nel prossimo sprint vedremo di capire se è possibile ottimizzare le richieste per fargli utilizzare il minor quantitativo di dati possibile, ed in tal caso potremmo considerare di diminuire l'intervallo. Altrimenti, dovremo passare ad un piano di smartproxy più sostanzioso in termini di gb di richieste disponibili
![image](https://github.com/marconicivitavecchia/IFC-Backend-dev/assets/92986550/914d6854-b949-4734-bd8a-d3d8b8353c04)

**Comment by wbigger** [comment]
Rispondendo anche all'altra storia di @FThinker #2, sarebbe carino fare un semplice sistema di AI che apprende quando è più probabile che ci saranno più richieste e regolarsi di conseguenza. Altrimenti, nel caso in particolare dello streamer, potrebbe essere utile prevedere una funzione che accende/spegne il controllo, perché tanto in quel caso il contatore si usa solo per pochi minuti ma deve essere reattivo.

**Comment by FThinker** [comment]
L'opzione per attivare/disattivare il controllo è un'ottima idea, alla quale onestamente non avevamo pensato.
Quanto all'AI, intende utilizzarla per capire in che fasce orarie si ricevono in media più follower e quindi modificare l'intervallo con cui il codice esegue i controlli?

**Comment by wbigger** [comment]
sì, l'idea della AI è fare un periodo di prova di qualche mese in cui si raccolgono i dati su quando le persone generalmente mettono i like, quindi allenare una rete neurale a predire automaticamente quando diminuire ed aumentare l'intervallo.

La stessa cosa si può fare anche a mano, mettendo delle fasce orali o settimanali, ma in questo modo sarebbe automatizzato.

**Comment by FThinker** [comment]
Nel prossimo sprint ci darò un'occhiata

**Comment by wbigger** [comment]
Noi a scuola usiamo [scikit-learn](https://scikit-learn.org/), semplice da usare e adatta a questo genere di applicazioni.
