### ISSUE TITLE
[4] Come utente, vorrei che il contatore funzionasse sempre, senza che occorrano dei blocchi.

### ISSUE THREAD

**Issue by FThinker** [marconicivitavecchia/IFC-Backend-dev#2]
1) Capire in che modo Instagram limita/blocca l'utente quando esegue troppe richieste
2) Trovare un modo per aggirare il blocco dell'IP di Instagram ed, in caso, implementarlo

**Comment by FThinker** [comment]
@wbigger https://www.pyproxy.com/residential/

**Comment by FThinker** [comment]
Instagram può bloccare temporaneamente l'IP se si inviano troppe richieste.
Se si fa scraping mentre si è loggati in un account, può anche fare un hardware ban, ma questo non è il nostro caso.
Con un server proxy possiamo cambiare ip ciclicamente ed evitare di essere bloccati, ma diminuire il wait time per le richieste sotto i 10 secondi potrebbe comunque essere rischioso.

**Comment by wbigger** [comment]
Ho attivato e caricato un po' di credito su [smartproxy.com](https://dashboard.smartproxy.com/) con l'utente scraper.
Putroppo ieri mattina ho sbagliato a configurare le impostazioni della mail e non accettava messaggi da fuori l'organizzazione, quindi abbiamo perso eventuali gift di benvenuto.

C'è un 14 giorni di money back. Per favore @FThinker in questi giorni dà un'occhiata se funziona come ci si aspetta in modo che, se non è quello che ci serve, chiediamo i soldi indietro.

**Comment by FThinker** [comment]
Certamente, appena ho un attimo lo provo. Comunque, potrebbe aggiungere
anche Italia nel repository? Il suo username è Kylessh

Il giorno dom 12 nov 2023 alle ore 18:35 Claudio Capobianco <
***@***.***> ha scritto:

**Comment by FThinker** [comment]
Non è nemmeno nell'organizzazione del Marconi

Il giorno dom 12 nov 2023 alle ore 19:12 Filippo Taiani <
***@***.***> ha scritto:

**Comment by wbigger** [comment]
L'ho aggiunto al team backend, credo che dovrebbe automaticamente entrare a far parte dell'organizzazione se accetta l'invito @Kylessh

**Comment by FThinker** [comment]
Ora il codice funziona senza intoppi. Cambiando IP ogni volta che facciamo una richiesta non veniamo più bloccati.
Ogni tanto appaiono degli errori in console, non sono sicuro del perché succeda, ma credo che siano legati al cambiamento di IP da parte del proxy. In ogni caso questi errori non sono un problema, perché il codice continua l'esecuzione tranquillamente e gli errori in sé sono piuttosto rari.


![Image](https://github.com/marconicivitavecchia/IFC-Backend-dev/assets/94018178/2aadb41f-29d9-4a7b-aeb3-5f149ad8d77d)
