### ISSUE TITLE
[2] Come sviluppatore del team Frontend, vorrei poter ottenere il dato del numero di follower

### ISSUE THREAD

**Issue by FThinker** [marconicivitavecchia/IFC-Backend-dev#3]
Creare un endpoint che permetta alla Frontend di ottenere il numero di follower.

**Comment by FThinker** [comment]
Abbiamo già l'applicazione Express, bisogna soltanto fare un endpoint per la frontend.

**Comment by Rpinnkss** [comment]
![Image](https://github.com/marconicivitavecchia/IFC-Backend-dev/assets/124357976/7360232d-a71b-4cb3-bc9e-f6a41c052649)
